json.email @user.email
json.id @user.id
json.auth_token @user.authentication_token
json.username @user.username
json.level @user.level
json.desc @user.desc
json.webchat @user.webchat
json.github @user.github
json.avator @user.avator
